//
// CharactersByCatergoryAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class CharactersByCatergoryAPI {

    /**
     Characters List by Category
     
     - parameter category: (query) name of the show 
     - parameter limit: (query) limit of page (optional)
     - parameter offset: (query) offset of page (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func charactersGetByCategory(category: String, limit: Int? = nil, offset: Int? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: [ModelCharacter]?, _ error: Error?) -> Void)) -> RequestTask {
        return charactersGetByCategoryWithRequestBuilder(category: category, limit: limit, offset: offset).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Characters List by Category
     - GET /characters/
     - parameter category: (query) name of the show 
     - parameter limit: (query) limit of page (optional)
     - parameter offset: (query) offset of page (optional)
     - returns: RequestBuilder<[ModelCharacter]> 
     */
    open class func charactersGetByCategoryWithRequestBuilder(category: String, limit: Int? = nil, offset: Int? = nil) -> RequestBuilder<[ModelCharacter]> {
        let localVariablePath = "/characters/"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": limit,
            "offset": offset,
            "category": category,
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ModelCharacter]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
